### ISSUE TITLE
CLI for load balancers

### ISSUE THREAD

**Issue by vielmetti** [StackPointCloud/packet-cli#454] opened 2024-03-05 15:46 UTC
### What problem are you facing?

Automation of setup and configuration of the Equinix load balancer (LBaaS)

### How could the Equinix Metal CLI help solve this problem?

Using the documentation provided at

https://github.com/equinix/lbaas-api-docs

add a set of "metal load-balancer" commands that would set up,
configure, modify, and tear down load balancers, for CI automation
or for testing.

**Comment by displague** [comment] 2024-05-02 16:08
Thanks @vielmetti 

Closing this as a duplicate of #411

**Closed as completed by displague** 2024-05-02 16:08 UTC
Labels: enhancement
